import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useLocale } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}
export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  const localActive = useLocale();

  return (
    <html lang={localActive}>
      <body
        className={inter.className}
        dir={localActive === "ar" ? "rtl" : "ltr"}>
        <div className="flex flex-col min-h-screen flex-grow mt-20 max-w-4xl mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
